<?php

namespace AppBundle\Repository;

/**
 * billRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class billRepository extends \Doctrine\ORM\EntityRepository
{
}
