<?php

namespace AppBundle\Repository;

/**
 * detailbillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class detailbillRepository extends \Doctrine\ORM\EntityRepository
{
}
