<?php

namespace AppBundle\Repository;

/**
 * SaleOffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleOffRepository extends \Doctrine\ORM\EntityRepository
{
}
